#!/usr/bin/env python3

import sys


def print_msg(message, level=None):
    levels = ['Error', 'Info']
    if level not in levels:
        print(message)
    else:
        length = max(len(x) for x in levels)

        print('[ {l:{length}} ] {m}'.format(l=level, length=length, m=message))

# Find the temporary file
commit_msg_filepath = sys.argv[1]

# Open the file
with open(commit_msg_filepath, 'r') as f:
    line = f.readline()

    if line[0].capitalize() != line[0]:
        print_msg('Commits must start with a capital letter', 'Error')
        print_msg('Exiting now', 'Info')
        sys.exit(1)

    else:
        sys.exit(0)
