#!/usr/bin/env python3

import sys


def print_msg(message, level=None):
    levels = ['Error', 'Info']
    if level not in levels:
        print(message)
    else:
        length = max(len(x) for x in levels)

        print('[ {l:{length}} ] {m}'.format(l=level, length=length, m=message))

# Create an error counter
error_count = 0

# Find the temporary file
commit_msg_filepath = sys.argv[1]

# Open the file
with open(commit_msg_filepath, 'r') as f:
    line = f.readline()

    if line[0].capitalize() != line[0]:
        print_msg('Commit subject must start with a capital letter', 'Error')
        error_count += 1

    if '.\n' in line or '.' == line[-1]:
        print_msg('Commit subject should not end with a period', 'Error')
        error_count += 1

    if len(line) >= 50:
        print_msg('Commit subject must be less than 50 characters', 'Error')

if error_count:
    print_msg('Commit not acceptable', 'Info')
    sys.exit(error_count)
else:
    print_msg('Commit acceptable', 'Info')
